FROM gitlab-registry.nautilus.optiputer.net/prp/jupyterlab
LABEL maintainer="Daniel Crawl <danielcrawl@gmail.com>"

RUN set -x \
    conda install --quiet --yes \
        argparse \
        imutils \
        nbgitpuller \
        opencv-python \
        requests
